app:
    name: auth
    namespace: hci

image:
  repository: ghcr.io/fpmi-hci-2023/auth:latest
  tag: latest
  pullPolicy: Always
  pullSecretName: github-container-registry
  dockerconfigjson: |
    ewogICJhdXRocyI6CiAgICB7CiAgICAgICJnaGNyLmlvIjoKICAgICAgICB7CiAgICAgICAgICAiYXV0aCI6ImNtbGphR0Z5WkMxdmJqcG5hSEJmTVdoaFNGTm1UamMxTVZKVFoxVm9jR053YlRrek1GSTVZa1ZFTUhkQk0yWXdORXB6IgogICAgICAgIH0KICAgIH0KfQ==

ports:
  - name: http
    protocol: TCP
    targetPort: http
    port: 8080
    containerPort: 8080
  - name: grpc
    protocol: TCP
    targetPort: grpc
    port: 4000
    containerPort: 4000

service:
  type: ClusterIP

secret:
  enabled: true
  type: Opaque
  data:
    AES: "4h3tHL510DJjcbHS+7eErUL9Gtb8WnRyyC5ARoYqIJ0="
    DB_CONN_STRING: "host=localhost port=5432 user=hci password=E8n930d1SdXeOmZMLnQtKeGVegqfNXql05xyLi1I6vSS12KLa3Tiw3DgI2FWTf3m dbname=auth sslmode=disable"
    SECRET: "35ACCE14DB27AE6B6F88BEC45CC41"

configMap:
  enabled: true
  data:
    HOST: "localhost"
    TTL_ACCESS: "60"
    TTL_REFRESH: "3600"

replicaCount: 1
podAnnotations: {}

probes:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

ingress:
  enabled: false
