app:
    name: auth
    namespace: hci

image:
  repository: ghcr.io/fpmi-hci-2023/auth:latest
  tag: latest
  pullPolicy: Always
  pullSecretName: github-container-registry
  dockerconfigjson: |
    ewogICJhdXRocyI6CiAgICB7CiAgICAgICJnaGNyLmlvIjoKICAgICAgICB7CiAgICAgICAgICAiYXV0aCI6ImNtbGphR0Z5WkMxdmJqcG5hSEJmTVdoaFNGTm1UamMxTVZKVFoxVm9jR053YlRrek1GSTVZa1ZFTUhkQk0yWXdORXB6IgogICAgICAgIH0KICAgIH0KfQ==

ports:
  - name: http
    protocol: TCP
    containerPort: 8080

service:
  type: ClusterIP
  name: http
  protocol: TCP
  port: 8080
  targetPort: http

secret:
  enabled: false

configMap:
  enabled: false

replicaCount: 1
podAnnotations: {}

probes:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

ingress:
  enabled: false
