{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth.name" . }}-secret
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}