apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.name" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
      port: {{ .port }}
    {{- end }}
  selector:
    {{- include "sample.selectorLabels" . | nindent 4 }}
