apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth.name" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "auth.selectorLabels" . | nindent 4 }}
